
base:
  generate_prompt:
    "
    {% if user_input %}
    ## User input:
    {{user_input}}
    {% endif %}

    ## Modified files:
    {{files}}

    {% if diff %}
    ## Diff message:
    {{diff}}
    {% endif %}

    {% if last_diff %}
    ## Diff message:
    {{last_diff}}
    {% endif %}

    ---
    Please generate a git commit message based on the infomation above, keeping it within 50 words.
    Always in English
    
    ## Example
    ```
    feat: {add new functionality}
    fix: {resolve specific bug}
    optimize: {improve performance}
    docs: {update documentation}
    ```
    "

  summarize_prompt:
    "
    {{long_message}}

    ---
    Please generate a git commit message based on the infomation above, keeping it within 50 words.
    Always in English

    ## Example
    ```
    feat: {add new functionality}
    fix: {resolve specific bug}
    optimize: {improve performance}
    docs: {update documentation}
    "