
base:
  generate_prompt:
    "
    {% if user_input %}
    ## User input:
    {{user_input}}
    {% endif %}

    ## Modified files:
    {{files}}

    {% if diff %}
    ## Diff message:
    {{diff}}
    {% endif %}

    {% if last_diff %}
    ## Diff message:
    {{last_diff}}
    {% endif %}

    ---
    Please generate a git commit message based on the above content, keeping it within 50 words.
    The commit message should meet the following requirements:
    - Concise and clear, no redundancy, describe the functionality changes and their purpose
    - Always in English
    - Use present tense
    - Use imperative mood
    - Start with specific commit types, keep the commit header concise without any filenames or other information
        - Start with `feat:` for feature changes (use this type in most cases unless it clearly fits the types below)
        - Start with `fix:` for bug fixes and issue resolutions
        - Start with `optimize:` for performance optimizations
        - Start with `docs:` for documentation-related changes
    ## Example
    ```
    feat: {add new functionality}
    fix: {resolve specific bug}
    optimize: {improve performance}
    docs: {update documentation}
    ```
    "

  summarize_prompt:
    "
    {{long_message}}

    ---
    Please generate a git commit message based on the changes above, keeping it within 50 words.
    The commit message should meet the following requirements:
    - Concise and clear, no redundancy, describe the functionality changes and their purpose
    - Always in English
    - Use present tense
    - Use imperative mood
    - Start with specific commit types, keep the commit header concise without any filenames or other information
        - Start with `feat:` for feature changes (use this type in most cases unless it clearly fits the types below)
        - Start with `fix:` for bug fixes and issue resolutions
        - Start with `optimize:` for performance optimizations
        - Start with `docs:` for documentation-related changes
    ## Example
    ```
    feat: {add new functionality}
    fix: {resolve specific bug}
    optimize: {improve performance}
    docs: {update documentation}
    "